- macros/cross_db_utils/split_part.sql
- macros/get_url_parameter.sql
resolves https://github.com/fishtown-analytics/dbt-utils/issues/15
> added get url parameter syntax plus cross-database version of split_part

- macros/geo/haversine_distance.sql
This calculates the distance between two sets of latitude and longitude.
The formula is from the following blog post:
http://daynebatten.com/2015/09/latitude-longitude-distance-sql/
> adding distance macro

- macros/sql/generate_series.sql
resolves:
https://github.com/fishtown-analytics/dbt-utils/issues/39#issuecomment-356361690
> fixed range bug in generate_series

- macros/web/get_url_parameter.sql
This fixes the `get_url_parameter` macro so that it works with 091
> Qualify the get url parameter util macro

- macros/sql/nullcheck_table.sql
> add namespace to macro

- dbt_project.yml
- macros/materializations/insert_by_period_materialization.sql
Fixes incompatibilities in `insert_by_period` materialization with 0.13.0 adapter calls and updates repo to require dbt version 0.13.0.
Fixes #127
> Upgrades insert_by_period materialization to dbt 0.13.0

- .circleci/config.yml
> hopeful fix for integration test suite

- README.md
> Show correct usage information for the dateadd macro

- README.md
- integration_tests/data/schema_tests/data_unique_combination_of_columns.csv
- integration_tests/models/schema_tests/schema.yml
- macros/schema_tests/unique_combination_of_columns.sql
I've had this macro lying around for a while, and there was a thread in dbt Slack recently which made me decide that it's probably time to open source it
> Add unique_combination_of_columns test

- README.md
- integration_tests/data/sql/data_safe_add.csv
- integration_tests/models/sql/schema.yml
- integration_tests/models/sql/test_safe_add.sql
- macros/sql/safe_add.sql
#125 looked pretty straightforward and fun to do. :) 
I wasn't sure about how to actually format the output of the macro (re: spacing / style) though, so take a closer look there.
I'm also not super sure how running these tests work, though I'm hoping that CI will pick it up and run them? 🤞
> Add safe add macro

- README.md
I noticed a url wasn't working on the dbt_utils README today. I made a quick PR to fix that. Let me know if I need to change anything!
> Change some docs urls on README.md

- integration_tests/README.md
otherwise the dbt_utils is undefined when running
> Update docs, include dependency installation

- README.md
> Fix minor copy-paste typo in README.md

- .github/issue_template/bug_report.md
- .github/issue_template/feature_request.md
I think nudging this when someone creates an issue might encourage more contributions
> Add a question to issue templates

- run_test.sh
I ran this script without reading it very carefully and it turns out it deletes your profiles.yml if it exists. That's not very cool.
> do not default to breaking my profiles.yml

- CHANGELOG.md
- run_test.sh
This is a:
Update the changelog as part of an 0.5.1 release. Also make our tests more strict, in line with other packages we are updating.
> Prepare for 0.5.1 release

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/dbt_minor_release.md
- .github/ISSUE_TEMPLATE/utils_minor_release.md
- .github/pull_request_template.md
- RELEASE.md
> Documentation update

- README.md
> Cross-db-compatible example date_spine code in readme

- CHANGELOG.md
- README.md
- integration_tests/models/sql/test_star.sql
- integration_tests/models/sql/test_star_aliases.sql
- macros/sql/star.sql
This is a:
This picks up work from #281 (via @mdimercurio) and polishes it off given the more recent changes to this macro. While here, I also improved the docs a little.
> Allow star macro to be case insensitive. Improve docs while we're here.

- README.md
This is a:
Broken links really bugging me
> fix broken README anchor links

- macros/schema_tests/accepted_range.sql
This is a duplicate of #391 to merge against latest master. Full description in original PR.
> Cherry Pick: Log whole row in accepted range

- README.md
This is a:
Closes https://github.com/dbt-labs/dbt-utils/issues/400
> Update all FA references to dbt-labs references in Readme

- README.md
> fix broken or missing links in README

- .github/pull_request_template.md
> Update pull_request_template.md to reference `main` vs `master`

- README.md
This is a:
Simple typo in usage code.
> Update README.md (typo in usage code)

- .github/pull_request_template.md
- CHANGELOG.md
- README.md
- integration_tests/data/cross_db/data_any_value_expected.csv
- integration_tests/models/cross_db_utils/schema.yml
- integration_tests/models/cross_db_utils/test_any_value.sql
- macros/cross_db_utils/any_value.sql
This is a:
Resolves #497 
Necessary for usage in metrics package
> Add any value

- README.md
Closes #544
Re-do #560 -- merging into `main` branch instead.
> fix / added documentation about listagg macro to readme

- README.md
Re-do #555 -- merging into `main` branch instead.
> Fix link to macro section

- run_test.sh
Closes https://github.com/dbt-labs/dbt-utils/issues/540
Re-do https://github.com/dbt-labs/dbt-utils/pull/545 -- merging into main branch instead.
> Fail integration tests appropriately

- CHANGELOG.md
This is an:
The changelog is a little behind, so getting it up-to-date
> Update changelog for 0.8.4

- CHANGELOG.md
> Update changelog for dbt-utils v0.8.5

- README.md
- Provided example of optional where clause in get_columns_values
This is a:
Fixes #618
> Add where clause example

- README.md
> Added more in depth pivot example

- CHANGELOG.md
> Update CHANGELOG for v1.1.1

- .github/workflows/create-table-of-contents.yml
resolves #886
This is a:
[All commits](https://github.com/dbt-labs/dbt-utils/commits/main/) in the `main` branch should be ✅ , but we have guaranteed ❌ right now.
Disable the failing GitHub Action until we've got time and motivation to get it working again.
> Disable auto-generation of table of contents (TOC)

- .github/pull_request_template.md
resolves #906
This is a:
We have a lot of checklist items related to adding tests and running them against different warehouses. This makes it more onerous to read and complete the checklist.
Simplify the checklist by aligning more closely with the PR checklists for dbt-core, dbt-adapters, etc.
- [N/A] I have run this code in development and it appears to resolve the stated issue
- [N/A] This PR includes tests, or tests are not required/relevant for this PR
- [N/A] I have updated the README.md (if applicable)
> Simplify the PR checklist in relation to testing

- .github/pull_request_template.md
resolves #910
The PR template of dbt-utils has a single section for the main body of the description:
- Description & motivation
But dbt-core, dbt-adapters, etc. have two sections:
- Problem
- Solution
The latter allows the contributor to separate the design decisions of the implementation from the problem that it is trying to solve. This makes it easier for the contributor to write the PR description. It also makes it easier for others to read (code reviewers, users, etc.)
Adopt the standard established by [dbt-core](https://github.com/dbt-labs/dbt-core/blob/a677abd5e84bd8e5d6ed3cec0903345e226d9462/.github/pull_request_template.md), [dbt-adapters](https://github.com/dbt-labs/dbt-adapters/blob/a2292c8ec76e4c9f03869ad95817a2ad82dfb34b/.github/pull_request_template.md), etc in order to make …
> Align the PR description with dbt-core, dbt-adapters, etc.

- CHANGELOG.md
Update changelog for 1.3.0 release
> Update changelog for 1.3.0

- README.md
resolves #994
Two issues:
- The relevant code example was removed in https://github.com/dbt-labs/docs.getdbt.com/pull/6961
- The hyperlink is stale anyways
Replace the hyperlink with the explicit example.
> Update example for `unique` data test with concatenation of column names
