dbt-labs/dbt-utils

README.md
dbt_project.yml
macros/schema_tests/equality.sql

Changes:
- `ref()` now returns a `dbt.utils.Relation`, which has `name` and `schema` as properties

compatibility with 0.9.0

---

README.md
macros/schema_tests/cardinality.sql
macros/schema_tests/cardinality_equality.sql

This custom schema test macro checks to see if the cardinality of one field in a model exactly matches the cardinality of a chosen field in a different model.

Add cardinality equality schema test

---

macros/cross_db_utils/current_timestamp.sql
macros/cross_db_utils/dateadd.sql
macros/cross_db_utils/split_part.sql
macros/datetime/date_spine.sql

This makes `date_spine`, in addition to the other macros which use `adapter_macro` work with dbt 0.9.1

prefix adapter macro with package name (for 091)

---

README.md
macros/sql/get_tables_by_prefix.sql

Solution suggested by @drewbanin, enhanced with "exclude" parameter.

get_tables_by_prefix, ideal for union_tables jobs

---

README.md
macros/sql/generate_series.sql

addresses https://github.com/fishtown-analytics/dbt-utils/issues/33
have tested this on redshift, bigquery, postgres, and snowflake. the sql is pretty generic so fortunately no cross-db rewrites to worry about.

added new generate_series macro

---

README.md
macros/schema_tests/recency.sql

this is super-cool--uses two cross-db-utils that already existed :)

added recency schema test

---

README.md
macros/sql/get_column_values.sql

Before dbt 0.9.0 dropped, there was no way to `return` non-string values from macros. Since the `return` function works like a charm now, we should definitely be using it here.

Use `return` in get_column_values

---

macros/web/get_url_parameter.sql

This alters the `get_url_paramater` macro to return NULL instead of an empty string when no relevant parameters are found in the URL being parsed.

Have get url paramater macro return null when blank

---

macros/datetime/date_spine.sql

Snowflake requires that the `row_number()` window function uses an `order by` clause
Test with:

fix for orderby on snowflake

---

macros/cross_db_utils/datediff.sql

https://github.com/fishtown-analytics/dbt-utils/issues/49
Just read the docs and confirmed that the argument ordering for redshift and bigquery is opposite for the two datetime fields. Very annoying, but an easy fix.

fixed issue 49

---

README.md

Updated description + usage for star macro to clarify that one needs to write
```select {{dbt_utils.star(from=table,except=[]) from table```
The star macro only replaces the star, not the entire select statement. Previous wording implied that the macro would generate the entire table expression, cf. `dbt_utils.union_tables`.
An alternative approach would be to change the underlying code to actually generate an entire select statement, including the words `select` and `from {{from}}` in the compiled output, but I think there are compelling use cases where we want a star macro coupled with some basic calculation / casting / field population in the same CTE, especially if we're using `dbt_utils.star` to exclude a field that requires slight modification.

star macro readme

---

macros/sql/pivot.sql

The example code doesn't match the example output, because it's looking for colours in the size column. This update fixes it as per the example.

pivot example bug

---

macros/schema_tests/equality.sql
macros/sql/star.sql
macros/sql/union.sql

These changes short-circuit macro execution during the parsing of macros which do not modify the graph. 
dbt is smart enough skip running `statement` blocks during parsing, but it _does_ execute adapter functions like `get_columns_in_table`. As a result, there could be a very appreciable delay between typing `dbt run` and seeing the first lines of output from dbt.
For one project we experimented with, this brought the time-to-stdout down from 25 mins to 30 seconds o_0.
Thanks to @HarlanH for help with testing these changes.

don't query the database during parsing

---

README.md
macros/materializations/insert_by_period_materialization.sql

Adding a materialization to help build large models, by inserting records one period (day, week etc.) at a time

Add insert-by-period materialization

---

README.md
macros/materializations/insert_by_period_materialization.sql

The `in` filter was added to jinja in [v2.10.0](https://github.com/pallets/jinja/blob/master/CHANGES.rst#version-210), but dbt currently has a requirement on jina >= 2.8. Some folks might not have installed dbt for a while, and jinja can fail hard with this error when the `in` filter is used:
```
Compilation Error in macro unknown (materializations/insert_by_period_materialization.sql)
no test named 'in'
line 51
{%- if not '__PERIOD_FILTER__' is in sql -%}
```
This PR uses the built-in `.find` method on Python strings to avoid using partially supported jinja functionality.

fix for old versions of jinja

---

README.md
dbt_project.yml
integration_tests/data/sql/data_unpivot.csv
integration_tests/data/sql/data_unpivot_expected.csv
integration_tests/models/sql/schema.yml
integration_tests/models/sql/test_unpivot.sql
macros/sql/unpivot.sql

This macro adds functionality similar to pandas [melt](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.melt.html) function. It essentially "un-pivots" a table from wide-format to long-format.

Add "unpivot" macro

---

README.md
dbt_project.yml
macros/sql/star.sql

In the current implementation of the `star` macro, if you call the macro two distinct times referencing different tables that have overlapping field names, the model will error out since the `star` macro doesn't qualify the field names with a table alias (e.g. `ERROR:  column reference "column_name" is ambiguous`). This PR adds in an optional `relation_alias` argument to prefix all generated field names using `star` with an arbitrary table alias.

Star macro optional alias argument

---

.circleci/config.yml
integration_tests/Makefile
integration_tests/data/sql/data_union_expected.csv
integration_tests/data/sql/data_union_table_1.csv
integration_tests/data/sql/data_union_table_2.csv
integration_tests/models/sql/schema.yml
integration_tests/models/sql/test_get_column_values.sql
integration_tests/models/sql/test_union.sql
integration_tests/models/sql/test_union_base.sql
macros/cross_db_utils/literal.sql
macros/sql/union.sql

make union work on bq

---

macros/sql/unpivot.sql

Excluding the last column of a table in the unpivot macro would add an additional `union all` to the end.

fix for excluding last column in unpivot macro

---

README.md
integration_tests/macros/tests.sql
integration_tests/models/cross_db_utils/schema.yml
integration_tests/models/datetime/schema.yml
integration_tests/models/materializations/schema.yml
integration_tests/models/schema_tests/schema.yml
integration_tests/models/sql/schema.yml
integration_tests/models/web/schema.yml
macros/schema_tests/equality.sql

Updated all the schema.yml files, and schema.yml examples to be V2 of the schema.
Had to update a couple of the schema tests in the integration tests to make them play nicely.

Upgrade schema.yml to v2

---

.circleci/config.yml
integration_tests/data/sql/data_union_expected.csv
integration_tests/data/sql/data_union_table_1.csv
integration_tests/data/sql/data_union_table_2.csv
integration_tests/models/sql/test_unpivot.sql
macros/sql/union.sql
macros/sql/unpivot.sql

- do not use `safe_cast` when inappropriate ([see here](https://github.com/fishtown-analytics/dbt-utils/pull/112#issuecomment-452946608)) (union_tables, unpivot)
- improve `union_tables` integration test
- fix `union_tables` for Snowflake
- add `unpivot` integration test -- this was _disabled_ before, which was terrible
Note that this changes the behavior of `unpivot` slightly. Duplicate column names with different casing are no longer permitted, but I think that's a fair assumption to make.

fix errant uses of safe_cast

---

README.md

I've added a short _Getting Started_ section to the README.md to guide new users of dbt on how this package should be used with their project.

Improve README.md for newcomers

---

README.md
integration_tests/models/sql/test_nullcheck_table.sql
macros/cross_db_utils/_is_relation.sql
macros/schema_tests/equality.sql
macros/sql/get_tables_by_prefix.sql
macros/sql/get_tables_by_prefix_sql.sql
macros/sql/nullcheck_table.sql
macros/sql/star.sql
macros/sql/union.sql
macros/sql/unpivot.sql

* Fixes #129
* Closes #132
* Some breaking changes to contracts used by helper macros

Replace deprecated adapter methods with relations

---

README.md
macros/sql/pivot.sql

Indicates whether to surround column aliases with double quotes or not.

Added quote_identifiers argument

---

macros/cross_db_utils/intersect.sql

I want to use this macro in the new dbt-audit-helper package, [here](https://github.com/fishtown-analytics/dbt-audit-helper/blob/master/macros/check_equality.sql#L46). Currently I'm installing from a branch to get it to work (see [here](https://github.com/fishtown-analytics/dbt-audit-helper/blob/master/packages.yml))

Add intersect macro

---

macros/cross_db_utils/datatypes.sql

Added the following cross db macros.
* type_float
* type_bigint
* type_int
We needed these macros to be build cross compatibility with Redshift and BigQuery.

Added float and bigint datatype conversions

---

README.md
integration_tests/data/sql/data_unpivot.csv
integration_tests/data/sql/data_unpivot_expected.csv
integration_tests/data/sql/data_unpivot_original_api_expected.csv
integration_tests/models/sql/schema.yml
integration_tests/models/sql/test_unpivot_original_api.sql
macros/sql/unpivot.sql

This makes `dbt_utils.unpivot` a bit more like `pandas.melt` by adding the ability :
- to name the resulting columns
- to remove some columns from the operation

Adds 3 parameters to unpivot: remove, field_name, value_name

---

README.md

These installation instructions are notably much lighter than what was here before, since I've also opened a [PR](https://github.com/fishtown-analytics/hub.getdbt.com/pull/120) on the Hub site to add some instructions there.
If you're happy with this copy, I'll use it across all the packages we have on Hub – so expect lots of similar PRs :)
One thing to consider is that when you view this README on the hub site, it will have two sets of installation instructions 🤷‍♀

Point to hub for installation instructions

---

README.md
integration_tests/models/schema_tests/schema.yml
macros/schema_tests/expression_is_true.sql

An optional parameter 'condition' can be passed to the 
'expression_is_true' macro to assert the expression for all records 
which meet a condition. Closes #146
**Checklist**

support extra parameter 'condition' on 'expression_is_true' macro

---

macros/sql/get_tables_by_prefix_sql.sql

This helps when searching for schemas on Snowflake

get_tables_by_prefix: Make schema case insensitive

---

README.md
integration_tests/tests/logger/assert_pretty_output_msg_is_string.sql
integration_tests/tests/logger/assert_pretty_time_is_string.sql
macros/logger/log_info.sql
macros/logger/pretty_log_format.sql
macros/logger/pretty_time.sql
macros/materializations/insert_by_period_materialization.sql

I thought about how to test this, but it gets pretty hard given the output depends on the clock time. I wanted to do a regex match on the output, but Jinja doesn't support this.
In the end, I thought it would just be easiest to test if the output is a string 🙂

Add utils for logging to the command line

---

integration_tests/tests/logger/assert_pretty_output_msg_is_string.sql
integration_tests/tests/logger/assert_pretty_time_is_string.sql

- use `limit 0` instead of `where false`

Fix for pretty logger integration tests

---

README.md
integration_tests/Makefile
integration_tests/models/sql/test_get_column_values.sql
macros/sql/get_column_values.sql

Closes #119
This PR updates the get column values macro to take an optional `default` argument that can be used when the ref'd relation does not already exist. This is notable in cases when running `dbt compile`. 
Passing tests are: https://circleci.com/gh/fishtown-analytics/dbt-utils/330?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Resolve "get_column_values returns an error if passed a `ref`, but the model has not been previously built"

---

macros/sql/get_tables_by_prefix_sql.sql

Adds database parameter

---

README.md
integration_tests/models/schema_tests/schema.yml
integration_tests/models/schema_tests/test_equal_column_subset.sql
macros/schema_tests/equality.sql

The `compare_columns` argument allows a user to specify a subset of
columns to compare when checking the equality of two models' data.
There are a few shortcomings of the previous implementation that this
helps to address. With the previous implementation:
- You cannot compare two ephemeral models, as the comparison depends
on the ability to introspect relation.
- If two models differ in a predictable and expected way (e.g., the
addition of a surrogate key column), you would have to create an
additional materialized model that selects all but the added column
in order to compare equality.

Add a compare_columns arg to the equality test

---

macros/sql/star.sql

A call to `{{ dbt_utils.star(this, relation_alias='x') }}` previously would produce something like:
```
x. 
"column1"
,
x. 
"column2"
,
x. 
"column3"
```
Now produces:
```
x."column1",
x."column2",
x."column3"
```
The latter plays more nicely with the readability of the compiled sql. No leading or trailing whitespace, and just a newline between each column reference.

Reduce whitespace in dbt_utils.star

---

macros/sql/groupby.sql

reducing whitespace in compiled SQL for legibility
select
foo.a 
, foo.b 
, foo.c 
, sum(foo.d)
from
foo 
{{group_by(n=3)}} 
now results in 
select
foo.a 
, foo.b 
, foo.c 
, sum(foo.d)
from
foo 
group by
1,2,3

Reducing whitespace in group_by

---

macros/cross_db_utils/current_timestamp.sql

This pr fixes issue https://github.com/fishtown-analytics/dbt-utils/issues/109

Use getdate instead of current_timestamp

---

README.md
integration_tests/models/sql/test_get_relations_by_prefix_and_union.sql
integration_tests/models/sql/test_get_tables_by_prefix_and_union.sql
integration_tests/models/sql/test_union_base.sql
integration_tests/models/sql/test_unpivot.sql
macros/sql/get_relations_by_prefix.sql
macros/sql/union.sql
macros/sql/unpivot.sql

Started off by adding an `include` parameter to `union`. But then when I was updating the docs I decided that having this macro named `union_tables` is silly so did some work to tidy that up. And then I did the same for `get_tables_by_prefix` and `unpivot`. Pretty happy with this pattern!
(This is probably the way we should have done this when we upgraded to 0.14.0, but ah well! This provides us a path to deprecate some macros though!)
I also tidied up some docs along the way.
Here's what happens when you use the old macros:
```
$ dbt run -m test_get_tables_by_prefix_and_union
Running with dbt=0.15.0
Found 35 models, 53 tests, 0 snapshots, 0 analyses, 260 macros, 0 operations, 43 seed files, 0 sources
14:22:57 | Concurrency: 1 threads (target='redshift')
14:22:57 |
14:22:57 | 1 of 1 START …
```

Replace references to tables to relations. Add include param to union

---

macros/cross_db_utils/datatypes.sql
macros/cross_db_utils/literal.sql
macros/sql/union.sql

This dramatically reduces whitespace when unioning a large number of tables.
Currently the whitespace is largely created by the initial looping to resolve relations and columns. This results in thousands of lines of whitespace in our current workflow - we believe this is actually resulting in a hard-limit on querying redshift in some workflows due to the query length as we get an ambiguous redshift error when adding columns.
Test before:
```sql
(
select
cast(
'"analytics"."analyst_charlie_briggs_scratch"."data_union_table_1"'
as 
varchar
) as _dbt_source_relation,
cast("id" as integer) as "id" ,
cast("name" as character varying(5)) as "name" ,
cast("favorite_number" as character varying(2)) as "favorite_number" ,
cast(null as character varying(5)) as "favorite_color" 
from …
```

Reduce whitespace in union macro

---

macros/sql/star.sql

One thing I extremely hate is the compiled output of the star macro, which looks extra ugly in dbt Docs 😢.
This PR gets rid of a bunch of unnecessary whitespace. 
Before:
```
select
"EVENT_TIME"
,
"PAGE_URL"
,
"GROUP"
,
"CATEGORY"
,
"BENCHMARK_INDEX"
,
"SCORE"
,
"INCLUDED_THINGS"
from dev.model.some_table
```
After:
```
select
"EVENT_TIME",
"PAGE_URL",
"GROUP",
"CATEGORY",
"BENCHMARK_INDEX",
"SCORE",
"INCLUDED_THINGS"
from dev.model.some_table
```

Clean up star macro

---

README.md
integration_tests/models/sql/schema.yml
integration_tests/models/sql/test_surrogate_key.sql
macros/sql/surrogate_key.sql

Per [this conversation](https://getdbt.slack.com/archives/C2JRRQDTL/p1584050118056100) in dbt Slack, I wanted to explore the idea of allowing the surrogate key macro to support lists, instead of the varargs method.
This PR:
* Adds a deprecation warning if the varargs method is used.
* Allows for a single list argument to the surrogate macro. 
* Updates the surrogate key tests.

Allow list input for surrogate key macro 

---

dbt_project.yml
integration_tests/dbt_project.yml

_[ Copied from #228 ]_
resolves #229 
I wanted to remove the `config-version` deprecation errors for users using the recently released 0.17.0 version of dbt. This PR adds that config version to the project file and also bumps the required dbt version.

set config-version: 2

---

macros/materializations/insert_by_period_materialization.sql

Opening instead of #215 (breaking tests due to dbt version change)
This PR fixes this deprecation warning:
```
* Deprecation Warning: The materialization ("insert_by_period") did not
explicitly return a list of relations to add to the cache. By default the target
relation will be added, but this behavior will be removed in a future version of
dbt.
For more information, see:
https://docs.getdbt.com/v0.15/docs/creating-new-
materializations#section-6-returning-relations
```

Return target relation in insert by period materialization

---

.circleci/config.yml
integration_tests/ci/sample.profiles.yml

* Connect to sandboxed, cost-controlled instances of Redshift, Snowflake, BigQuery
* Use same env var nomenclature that dbt uses for its integration tests

New env vars for integration tests

---

macros/cross_db_utils/_is_ephemeral.sql
macros/schema_tests/equality.sql
macros/sql/nullcheck_table.sql
macros/sql/star.sql
macros/sql/union.sql
macros/sql/unpivot.sql

We get questions about this semi-regularly, so we should just handle the error better.
- N/A: I have updated the README.md (if applicable)
- N/A I have added tests & descriptions to my models (and macros if applicable)
I did not add any test for this macro, since I can't figure out how to test _for_ a failure!
I also worry that I'm going to break someone's project somehow...

Handle ephemeral models better

---

macros/sql/get_tables_by_prefix_sql.sql

Opening instead of #223 (had to rebase for tests)
From @preston-hf
INFORMATION_SCHEMA is actually [documented](https://cloud.google.com/bigquery/docs/information-schema-tables) and it requires less permissions than `__TABLES_SUMMARY__` which is not standardized and seems to require the ability to read the table, where INFORMATION_SCHEMA is queryable with just metadata access.

Replace __TABLES_SUMMARY__ with INFORMATION_SCHEMA

---

macros/sql/pivot.sql

Opening in place of #213 as a rebase was needed to ensure the tests pass
From @DylanBaker 
> This PR adds a `distinct` argument to the pivot macro. When set to true, it adds `distinct` to the aggregate, immediately after the opening bracket.

Add distinct argument to pivot macro. fka #213

---

README.md
integration_tests/data/schema_tests/data_test_not_null_where.csv
integration_tests/data/schema_tests/data_test_unique_where.csv
integration_tests/models/schema_tests/schema.yml
macros/schema_tests/test_not_null_where.sql
macros/schema_tests/test_unique_where.sql

Opening in favor of #219, as I had to rebase to run the tests:
From @martinguindon
Add `not_null_where` and `unique_where` schema tests.
These slightly modified schema tests from core enables analysts to run these tests on a subset of records. These are useful to run tests on sources that may contain soft-deleted records, or to exclude known errors that cannot be fixed.

Add unique_where and not_null_where schema tests. fka #219

---

.github/ISSUE_TEMPLATE/dbt_minor_release.md
.github/ISSUE_TEMPLATE/utils_minor_release.md
.github/pull_request_template.md
CHANGELOG.md
RELEASE.md
dbt_project.yml
integration_tests/ci/sample.profiles.yml
run_test.sh

As per our discussions — fixing a process problem with documentation rather than fancy tech.
🚨 We need to update our default branches to get this right.

Update release flow

---

macros/cross_db_utils/identifier.sql
macros/sql/get_relations_by_prefix.sql
macros/sql/surrogate_key.sql
macros/sql/union.sql
macros/sql/unpivot.sql

This adds the package and model name to the surrogate key deprecation warning.
I tested by directly editing the macro in dbt modules after running deps. Produces:
> Running with dbt=0.17.1
Warning: the `surrogate_key` macro now takes a single list argument instead of multiple string arguments. Support for multiple string arguments will be deprecated in a future release of dbt-utils. The gitlab_snowflake.arr_changes_sfdc_account_monthly model triggered this warning.
Parsing on run start hooks...
Parsing on run end hooks...
Warning: the `surrogate_key` macro now takes a single list argument instead of multiple string arguments. Support for multiple string arguments will be deprecated in a future release of dbt-utils. The logging.stg_dbt_audit_log model triggered this warning.
Warning: the …

Add package and model name in surrogate_key warning

---

CHANGELOG.md
README.md
integration_tests/models/sql/test_get_tables_by_prefix_and_union.sql
macros/sql/get_relations_by_pattern.sql
macros/sql/get_relations_by_prefix.sql
macros/sql/union.sql

This is a:
I removed `union_tables` and `get_tables_by_prefix`, which we deprecated >6 months ago as part of [v0.2.4](https://github.com/fishtown-analytics/dbt-utils/releases/tag/0.2.4) in Dec 2019
I also removed `get_tables_by_pattern` — this was introduced in v0.5.0 and is functionally equivalent to `get_tables_by_pattern_sql`. Given few people would be using this macro (as it's a helper macro), we are going to go straight to removing it rather than deprecating it first.
We could also consider deprecating:
- The old arguments for `surrogate_key` macro: deprecated in v0.3.0 /  April 2020
- `identifier`: deprecation warning added in  v0.4.0 / April 2020 (deprecated before then but not marked as such)
Personally, I think we should wait until the _next_ version of utils to deprecate those

Remove some deprecated macros

---

CHANGELOG.md
macros/schema_tests/unique_combination_of_columns.sql

Added quote_columns=(true | false) flag to the unique_combination_of_columns.sql macro

---

CHANGELOG.md
README.md
run_test.sh

This PR prepares for 0.6.0 release.
Once this is merged, I'll create a PR to merge `dev/0.6.0` into `master` :)
(Probably could have done that as one PR in hindsight)

Prepare 0.6.0 release

---

CHANGELOG.md
integration_tests/data/sql/data_events_20180103.csv
integration_tests/data/sql/data_union_events_expected.csv
integration_tests/dbt_project.yml
integration_tests/models/sql/schema.yml
integration_tests/models/sql/test_get_relations_by_pattern.sql
macros/sql/get_tables_by_pattern_sql.sql

This is a:
We weren't handling the `schema_pattern` arg correctly. And it turns out that on BQ it's kind of annoying to handle it the right way. I think I got it though.
- n/a I have updated the README.md (if applicable)
- n/a I have added tests & descriptions to my models (and macros if applicable)
I added this:
Raw: `analysis/foo.sql`
```sql
{% set tables = dbt_utils.get_relations_by_pattern(
schema_pattern = '%',
table_pattern = '%'
) %}
{% for table in tables %}
select * from {{ table }}
{% endfor %}
```
Compiled:
```
select * from `unique-serenity-254521`.`dbt_claire`.`data_star_expected`
select * from `unique-serenity-254521`.`dbt_claire`.`data_test_relationships_where_table_1`
select * from `unique-serenity-254521`.`dbt_claire`.`data_unpivot`
...
```
LGTM :)

Handle schema pattern on BQ

---

CHANGELOG.md
macros/sql/get_tables_by_pattern_sql.sql

This is a:
Turns out that this line forces the argument to be the default value.
Closes [this issue on codegen](https://github.com/fishtown-analytics/dbt-codegen/issues/33)
I updated my local version of codegen to also use my local version of utils, and tested locally.
I also did a quick `cmf + f` to find any other instances of this, and couldn't see anything — would definitely appreciate a second set of eyes there

Remove errant default args from get_tables_by_pattern_sql

---

CHANGELOG.md
README.md
macros/schema_tests/unique_combination_of_columns.sql

This is a:
This PR adds `where` parameter to the `unique_combination_of_columns` schema test in order to support a `WHERE` clause that can be used to isolate the tuples on which the uniqueness for the combination of columns needs to be verified.

Added `where` parameter to the `unique_combination_of_columns` schema test

---

CHANGELOG.md
README.md
integration_tests/models/schema_tests/schema.yml
macros/schema_tests/expression_is_true.sql

Opening in favor of #226
This is a:
From #226:
> I love the expression_is_true schema test, but often it feels like the tests I use them for should be a child of the column I'm testing against, instead of the whole relationship. So I modified the expression_is_true test to do exactly that.
Left the original tests as is (no regressions), and added 2 more tests to test with condition set and without it.

Make expression_is_true test work as a column test

---

CHANGELOG.md
README.md
integration_tests/data/sql/data_star_aliases_expected.csv
integration_tests/dbt_project.yml
integration_tests/models/sql/schema.yml
integration_tests/models/sql/test_star_aliases.sql
macros/sql/star.sql

From #230 (had to create a new PR so I could rebase the changes)
----
I love the `star` macro! I often find myself excluding columns just so I can alias them. This leads to less DRY code than I'd like, so I extended star to take an optional dictionary `{colname:aliasname}` and it will then alias the columns as expected.

Allow aliasing individual columns from star macro.

---

CHANGELOG.md
README.md
integration_tests/data/cross_db/data_cast_bool_to_text
integration_tests/data/sql/data_unpivot_bool.csv
integration_tests/data/sql/data_unpivot_bool_expected.csv
integration_tests/models/sql/schema.yml
integration_tests/models/sql/test_unpivot_bool.sql
macros/cross_db_utils/cast_bool_to_text.sql
macros/sql/unpivot.sql

Opening in favor of #208 (stale PR)
This is a:

Bool unpivot

---

.circleci/config.yml
dbt_project.yml
run_test.sh

- Resolves #308
- Bumps upper bound to allow dbt v0.19.0, which has no breaking changes
- Since there are no breaking changes, I'd love to cut a patch release of dbt-utils that bumps its upper bounds _before_ the final release of v0.19.0. This would make it easier for folks to test v0.19.0-rc1, since it obviates the need to explicitly pass `--no-version-check`.
- ~I have updated the README.md (if applicable)~
- ~I have added tests & descriptions to my models (and macros if applicable)~

Allow dbt v0.19.0

---

macros/materializations/insert_by_period_materialization.sql
run_test.sh

Extends #319, fixup of #309 (v0.6.3)
This is a:
- Update `insert_by_period` in a way that should be compatible for v0.19.0 _and_ earlier versions. I'm hoping we can release this as a patch to 0.6.3, rather than a new minor version :) I tested on v0.19.0-rc1 and v0.18.1.
- Include a `--full-refresh` step to build `test_insert_by_period` twice
- ~I have updated the README.md (if applicable)~
- ~I have added tests & descriptions to my models (and macros if applicable)~

Fix: insert by period for 0.19

---

macros/materializations/insert_by_period_materialization.sql
run_test.sh

@jtcohen6 — this is what is broken, but I can't quite get it to work! not sure how to access the internals of the AdapterResponse class. Figured you would have a better idea than me :) 
Also — this would be classed as a breaking change, so we might want to write some logic about handling this on different versions of dbt to avoid the break.
I was curious as to how this snuck in, and went back to #309 — turns out it [silently failed](https://app.circleci.com/pipelines/github/fishtown-analytics/dbt-utils/199/workflows/4426f6ef-333b-4336-b3e3-31cff022dce4/jobs/700/parallel-runs/0/steps/0-105) back then! I think because the "test" step passed, even though the "run" step failed. Now that we are using `-x`, the job exits, causing other tests to fail, and the resultant error message.
I think the …

broken commit: update internals of insert by period

---

.circleci/config.yml
integration_tests/ci/sample.profiles.yml
macros/materializations/insert_by_period_materialization.sql
run_test.sh

resolves #315
- Use 5 threads (Postgres, Redshift) or 10 (Snowflake, BigQuery)—an arbitrary number!
- Allows us to run tests on different warehouses (Redshift, Snowflake, BigQuery) simultaneously rather than in sequence
- Removes the caching of dependencies. (a) I think it's pretty fast to install dbt. (b) Helpful if we need to test with a new (prerelease) version of dbt, without needing to manually invalidate cache. (c) I'm not entirely sure how to do these with workflows, and I know it can be tricky to share cache across concurrent jobs—[there are plenty of docs](https://circleci.com/docs/2.0/caching/) to read
This is a:

Switch to CircleCI workflow

---

CHANGELOG.md
macros/schema_tests/equality.sql

See: https://github.com/fishtown-analytics/spark-utils/issues/7
This is a:
If `equality` is comparing an ephemeral model with the `compare_columns` keyword argument, we want to avoid running `adapter.get_columns_in_relation(model)` entirely.
Currently, it is the default/fallback arg to `kwargs.get()`. Instead, we should place it inside a conditional that only runs if `kwargs.get(compare_columns)` returns none. I was under the impression that these were effectively the same, but this change actually fixes an integration test (`test_equal_column_subset`) on `dbt-utils` + `spark-utils`.
Why did this only break with Spark? Because `dbt-spark` uses `describe table [table_name]` to get the columns from a given table, a command that fails if the table does not exist. Most "core" adapters query …

Fix equality test with ephemeral model + explicit column set

---

CHANGELOG.md
integration_tests/tests/assert_get_query_results_as_dict_objects_equal.sql

This is a:
See: https://github.com/fishtown-analytics/spark-utils/issues/7
Unless a query contains `order by`, its order is not deterministic on analytical databases / data processing technologies. This test is currently failing on Spark even though `dbt_utils.get_query_results_as_dict()` works just fine.
I believe that `order by 1` is supported on all known adapters.
- ~I have updated the README.md (if applicable)~
- ~I have added tests & descriptions to my models (and macros if applicable)~

Fix: get_query_results_as_dict integration test

---

CHANGELOG.md
integration_tests/dbt_project.yml
integration_tests/macros/limit_zero.sql
integration_tests/tests/assert_get_query_results_as_dict_objects_equal.sql
integration_tests/tests/logger/assert_pretty_output_msg_is_string.sql
integration_tests/tests/logger/assert_pretty_time_is_string.sql
macros/schema_tests/at_least_one.sql
macros/schema_tests/cardinality_equality.sql
macros/schema_tests/expression_is_true.sql
macros/schema_tests/not_constant.sql
macros/schema_tests/relationships_where.sql

This is a:
MSFT's T-SQL has some weird quirks to it such as:
- subquery aggregate columns need aliases; and
- there is no boolean type, so there's no such thing as `true` and `false`. So in a few schema tests, I've replaced `true` with `1=1`; and,
- `limit 0` at the end of the query translates in TSQL to `SELECT TOP (0)`. If the purpose is to return zero rows, `WHERE 0=1` will accomplish the same more universally.

t-sql hacks that shouldn't break mainline behavior

---

CHANGELOG.md
README.md
macros/sql/get_relations_by_pattern.sql
macros/sql/get_relations_by_prefix.sql
macros/sql/get_tables_by_pattern_sql.sql

This is a:
I was trying to use this macro today like so:
```sql
{% macro cleanup_ci_relations(safe_mode=true) %}
{% set relations_to_drop = dbt_utils.get_relations_by_pattern(
schema_pattern='my_schema',
table_pattern='dbt\_%'
) %}
{% set sql_to_execute = [] %}
{% for relation in relations_to_drop %}
{% set drop_command %}
drop {{ relation.type }} {{ relation }} cascade;
{% endset %}
{% do log(drop_command, info=True) %}
{% do sql_to_execute.append(drop_command) %}
{% endfor %}
{% endmacro %}
```
However this line didn't work:
```sql
drop {{ relation.type }} {{ relation }} cascade;
```
Since `relation.type` compiled to None.
This fixes the issue, but I'm curious whether there's a smarter thing we should be doing here!
I also took the opportunity to update the docs to hint people towards …

Add relation type to get_relations_by_pattern and get_relations_by_prefix

---

CHANGELOG.md
README.md
integration_tests/models/sql/test_get_column_values.sql
macros/sql/get_column_values.sql

Opening in place of #289 — needed to rebase to get it to work, and while I was here I simplified the implementation a little
This is a:
Implement an `order_by` arg to `get_column_values`.  Fix up docs while here

Column values sort

---

integration_tests/data/cross_db/data_last_day.csv
integration_tests/models/cross_db_utils/test_last_day.sql
macros/cross_db_utils/last_day.sql

This is a:
The existing macro `last_day` does not support `quarter` because postgres does not support `quarter` interval. I've updated to use 3 months when datepart is quarter, so the same sql can be used in the supported databases.

support quarter in postgres last day

---

CHANGELOG.md
macros/schema_tests/sequential_values.sql

This is a:
Synapse doesn't have a `timestamp` type, instead `dbt_utils.type_timestamp()` should be used.

Hotfix sequential values timestamp

---

CHANGELOG.md
macros/cross_db_utils/concat.sql

This is a:
Previously merged in #296, but we moved it around to get the 0.6.5 release out

Simplify concat

---

.github/pull_request_template.md
CHANGELOG.md

This is a:
To get tsql-utils current with `0.6.5` (https://github.com/dbt-msft/tsql-utils/pull/49), I had to disable many new tests that went with new macros. When undispatched macros are added to dbt-utils, it requires two PRs to get the new macro working with TSQL:
1. a PR to dbt-utils to allow the new macro to be dispatched
2. a PR to tsql-utils adding the shim logic for the new macro.
My proposal would be to strive for all new proposed macros to have dispatch logic before merging. The rationale being:
- IIRC, releases can't be used for submodules, yet
- submodules are how the shim packages (tsql-utils, spark-utils, presto-utils) import dbt-utils.
This makes it hard to selectively add new functionality to the shim packages without taking all commits to master

Upfront ask to dispatch new macros

---

CHANGELOG.md
dbt_project.yml

This is a:
- dbt v0.21 (currently in beta) shouldn't have any breaking changes for `dbt-utils`, so we can add compatibility as a patch release
- ~I have "dispatched" any new macro(s) so non-core adapters can also use them (e.g. [the `star()` source](https://github.com/fishtown-analytics/dbt-utils/blob/master/macros/sql/star.sql))~
- ~I have updated the README.md (if applicable)~
- ~I have added tests & descriptions to my models (and macros if applicable)~

Bump upper bound to <0.22

---

README.md

This is a:
Updating README for schema tests to point to correct macros. Additional `test_` prefix possibly relating to latest v0.20.0 changes in which `not_null` now includes `where`

Update schema_tests links

---

CHANGELOG.md
integration_tests/models/sql/test_star.sql
macros/sql/star.sql

resolves https://github.com/dbt-labs/dbt-utils/issues/402
This is a:
This PR allows a user to put their `except` values in whatever case they want when calling them within `dbt_utils.star()`
`{{ dbt_utils.star(from=ref('my_model', except=["col_a","col_b"])` == `{{ dbt_utils.star(from=ref('my_model', except=["COL_A","Col_B"])`

PR - lowercase `except` values in star()

---

macros/sql/get_column_values.sql

Most database engines (e.g. all SQL Server versions) don't support grouping by the position of the column.
This is a:
The current version of get_column_values doesn't work on database engines other than the subset which supports the position of the column in GROUP BY statements.

use column name in group by in get_column_values

---

macros/sql/star.sql

This is a:
- [ X] bug fix PR with no breaking changes — please ensure the base branch is `master`
The feature added in 0.7.2 which allowed for star excludes to be case insensitive appears to have brought in an issue causing columns to get incorrectly dropped. https://github.com/dbt-labs/dbt-utils/issues/417
It looks like this is due to the |lower command turning a list into a string - this fixes that by looping over the columns to exclude and lowercasing them individually. 
- [ X] BigQuery

fix: in star make excludes a list

---

macros/schema_tests/not_null_proportion.sql
macros/sql/star.sql

Two changes on the not_null_proportion.
1. Changed the dispatch to use 'macro_namespace' to avoid deprecation warning
2. Changed the final select to be * instead of count(*) to avoid false positive results.
This is a:
- [X ] bug fix PR with no breaking changes — please ensure the base branch is `master`

fix: not_null_proportion test deprecation warning and performance 

---

macros/schema_tests/equality.sql

This is a:
- [-] new functionality — please ensure the base branch is the latest `dev/` branch
- [-] a breaking change — please ensure the base branch is the latest `dev/` branch

Fix SQL 42000 on Exasol

---

CHANGELOG.md
README.md
dbt_project.yml
integration_tests/tests/jinja_helpers/test_slugify.sql
macros/schema_tests/equality.sql

This is a:
This test cannot be used by databases that don't support `limit zero`

use `limit_zero` macro instead of `limit 0`

---

README.md

This is a:
The readme missed a link to the accepted_range test. This PR adds the missing link to achieve a complete documentation and easy lookup for developers.

Add missing link to accepted_range test in Readme

---

CHANGELOG.md
integration_tests/data/web/data_url_host.csv
macros/web/get_url_host.sql

This is a:
In my Segment page view data, we see `referrer` values such as `android-app://m.facebook.com/`. These seem to be specific for Android apps and take the place of `http://`. The current `get_url_host()` macro will return an `android-app://` value instead of the hostname for those referrer URLs. Be great if the `get_url_host()` macro handled those too!

Add handling for `android-app://` in `get_url_host()` macro

---

CHANGELOG.md
macros/materializations/insert_by_period_materialization.sql

This is a:
This removes an extra semicolon in the `insert_by_period` materialization that causes the initial materialization (or rematerialized due to a full refresh) to fail immediately after creating the empty table when running in Snowflake with a "_cannot unpack non-iterable NoneType object_" error.

Remove extra semicolon in `insert_by_period` materialization

---

CHANGELOG.md
integration_tests/models/sql/test_get_column_values.sql
macros/sql/get_column_values.sql

Resolves #424 - Mixed-quoting styles on Snowflake created an invalid `Relation` using the adapter
This is a:

Use the relation object passed into get_column_values, instead of making our own

---

CHANGELOG.md
dbt_project.yml
macros/sql/get_column_values.sql

This is a:
Fixes #304 
I think get_column_values should return default if not executing.
The issue I'm describing is that this function has a default parameter that will be returned if no data is found. But if DBT is not on execution mode, it will return an empty string
https://github.com/fishtown-analytics/dbt-utils/blob/c8389533cc7f00823c50d08d904cdfa5f714ec8b/macros/sql/get_column_values.sql#L17
Using this simple code will trigger a warning as columns will default to an empty string if no execute:
```
{% set rep_types = dbt_utils.get_column_values(source_table, 'rep_type', default=[]) %}
{{ dbt_utils.surrogate_key(columns) }} AS row_hash
```

return default in get_column_values if no execute

---

README.md
integration_tests/data/sql/data_star_prefix_suffix_expected.csv
integration_tests/models/sql/schema.yml
integration_tests/models/sql/test_star_prefix_suffix.sql
macros/sql/star.sql

This is a:
Just added optional `prefix` and `suffix` arguments to the star macro, so that the output fields will all be renamed as prefix ~ name ~ suffix (very similar to the `pivot` macro). 
This is helpful to me in that I can more easily know where columns came from. Morewover, I have a particular case where I am using `star` twice in the same CTE, and the columns included in each source relation that I'm joining/selecting from can have custom names. If there's any overlap between the two sources, we'll see an `ambiguous column` error without any prefix or suffix to distinguish them

add prefix and suffix arguments to star macro

---

integration_tests/data/sql/data_get_column_values_dropped.csv
integration_tests/dbt_project.yml
integration_tests/tests/sql/test_get_column_values_use_default.sql
macros/sql/get_column_values.sql

Resolves #444 
This is a:
The change I made in #440 to solve #424, in turn broke the fix introduced in #152/#119 to have a default when a model doesn't exist.
This:
- adds a test to validate behaviour when a model doesn't exist, to prevent future regressions. 
- goes back to the old approach of explicitly trying to load the relation (but using the convenience method) to check existence, instead of taking the not-None-ness of the input object at face value. 
Concerns: 
- I don't know why the integration tests aren't running, and I want them to! 
- The convenience method `load_relation` doesn't do anything differently to the old behaviour. I _think_ this means that anyone who has both #424 and #119 problems will still be stuck. But I haven't run into any of them yet, so we'll burn that …

Regression: Correctly handle missing relations in get_column_values

---

integration_tests/data/web/data_url_host.csv
macros/web/get_url_host.sql

This is a:
I accidentally merged #426 into next/minor instead of next/patch, even though it was backwards compatible.

Backport android url host

---

dbt_project.yml

Change upper bound of require-dbt-version to be < 1.1.0

---

README.md

I noticed that the docs were missing a ling for the `fewer_rows_than` schema test in the content section. I added the link here.
This is a:
- ~[ ] I have verified that these changes work locally on the following warehouses (Note: it's okay if you do not have access to all warehouses, this helps us understand what has been covered)~
- ~[ ] BigQuery~
- ~[ ] Postgres~
- ~[ ] Redshift~
- ~[ ] Snowflake~
- ~[ ] I followed guidelines to ensure that my changes will work on "non-core" adapters by:~
- ~[ ] dispatching any new macro(s) so non-core adapters can also use them (e.g. [the `star()` source]~(https://github.com/fishtown-analytics/dbt-utils/blob/master/macros/sql/star.sql))~
- ~[ ] using the `limit_zero()` macro in place of the literal string: `limit 0`~
- ~[ ] using `dbt_utils.type_*` …

Add link for fewer_rows_than schema test in docs

---

.gitignore
CHANGELOG.md

This is a:
makes dbt-utils local development easier!
~~- [ ] I have verified that these changes work locally on the following warehouses (Note: it's okay if you do not have access to all warehouses, this helps us understand what has been covered)~~
~~- [ ] BigQuery~~
~~- [ ] Postgres~~
~~- [ ] Redshift~~
~~- [ ] Snowflake~~
~~- [ ] I followed guidelines to ensure that my changes will work on "non-core" adapters by:~~
~~- [ ] dispatching any new macro(s) so non-core adapters can also use them (e.g. [the `star()` source](https://github.com/fishtown-analytics/dbt-utils/blob/master/macros/sql/star.sql))~~
~~- [ ] using the `limit_zero()` macro in place of the literal string: `limit 0`~~
~~- [ ] using `dbt_utils.type_*` macros instead of explicit datatypes (e.g. `dbt_utils.type_timestamp()` …

also ignore dbt_packages

---

CHANGELOG.md
macros/sql/date_spine.sql

This is a:
The macro date_spine was not compatible with the Athena connector because there was a comment using the syntax `/* ... */`
I replaced it with a Jinja comment block `{#...#}`

date_spine: transform comment to jinja

---

README.md

This is a:
The existing example code snippet for `get_query_results_as_dict` did not demonstrate accessing the result object by dictionary key.

Update get_query_results_as_dict example to demonstrate accessing columnar results as dictionary values

---

README.md

This is a:
Very simple Readme change to reflect the deprecation of the `not_null_where` test in v1.0.

Add note about not_null_where deprecation to Readme

---

README.md
macros/sql/union.sql

This is a:
Fixes #266. Using the `include` parameter in `union_relations` with columns names that don't exist in the relations will result in invalid SQL being generated. This PR adds logic to raise an exception if there are no columns to union.
There doesn't appear to be a good way to write a unit test to ensure that an exception is raise (https://github.com/dbt-labs/dbt-core/issues/3060), but this worked in my manual testing.

Have union_relations raise exception when include parameter results in no columns

---

README.md

Correct coalesce -> concatenation typo in readme

---

README.md
integration_tests/data/sql/data_star_aggregate.csv
integration_tests/data/sql/data_star_aggregate_expected.csv
integration_tests/models/sql/schema.yml
integration_tests/models/sql/test_star_aggregate.sql
macros/sql/star.sql

This is a:
The current implementation of the star macro always generates column aliases.  This limits its usage to the specified situation `select * from {{ref('my_model')}}`, replacing star (`*`) with the star macro. 
With the simple addition of a condition, I have modified the star macro so that a column alias will only be added if there is a prefix and/or a suffix specified.  This makes the star macro useful in other situations such as in WHERE or GROUP BY predicates such as: `select ... from {ref('my_model')}} where (*) not in (select ...`, replacing star (`*`) with the star macro.  
This should also be a non-breaking change, as if neither a prefix and/or suffix is specified, then the column name alias is the same as the actual column name.

Enhance usability of star macro by only generating column aliases when prefix and/or suffix is specified

---

CHANGELOG.md
integration_tests/data/cross_db/data_bool_or.csv
integration_tests/data/cross_db/data_bool_or_expected.csv
integration_tests/models/cross_db_utils/schema.yml
integration_tests/models/cross_db_utils/test_bool_or.sql
macros/cross_db_utils/bool_or.sql

This is a:
Needed for the metrics package

Add bool or cross db

---

macros/sql/union.sql

This is a:
(At least partially) Resolves #505 - we still don't know why this happens some times and not others, but at least this protects people who aren't even using include/exclude params.

Fix union_relations error when no include/exclude provided

---

README.md

very minor nit - update "an new" to "a new"

---

CHANGELOG.md
README.md
macros/sql/get_column_values.sql
macros/sql/union.sql

This is a:
As outlined in Issue #358, the `get_column_values` macro does not work on ephemeral models, but does not currently provide a meaningful compiler error to communicate the issue to the end user. Instead, the user sees the python exception: `Server error: 'NoneType' object has no attribute 'lower'`. This PR adds the `_is_ephemeral` test to provide a meaningful error to the user.

Add _is_ephemeral test to get_column_values

---

CHANGELOG.md
README.md
macros/sql/get_relations_by_pattern.sql
macros/sql/get_table_types_sql.sql
macros/sql/get_tables_by_pattern_sql.sql
macros/sql/union.sql

This is a:
- [X ] bug fix PR with no breaking changes — please ensure the base branch is `main`
- [ X] I have verified that these changes work locally on the following warehouses (Note: it's okay if you do not have access to all warehouses, this helps us understand what has been covered)
- [ X] BigQuery
- [ X] dispatching any new macro(s) so non-core adapters can also use them (e.g. [the `star()` source](https://github.com/fishtown-analytics/dbt-utils/blob/master/macros/sql/star.sql))
- [ X] using the `limit_zero()` macro in place of the literal string: `limit 0`
- [ X] using `dbt_utils.type_*` macros instead of explicit datatypes (e.g. `dbt_utils.type_timestamp()` instead of `TIMESTAMP`
- [ X] I have updated the README.md (if applicable)
- [ X] I have added tests & descriptions to my …

Typed materialized views as views

---

README.md
integration_tests/data/sql/data_deduplicate.csv
integration_tests/models/sql/test_deduplicate.sql
macros/sql/deduplicate.sql

This is a:
It occurred to me that quite often one might want to first filter a model and then deduplicate it. The requirement for `deduplicate` to take a relation (in order to be able to return the correct columns) makes this difficult. By adding an `alias` argument we allow the macro to find the columns from a relation but to select from a CTE.

Add `alias` argument to `deduplicate` macro

---

macros/sql/star.sql

This is a:
This PR is fixing the issue mentioned here: https://github.com/dbt-labs/dbt-utils/issues/506

fix issue 506 updating star.sql file

---

macros/sql/get_table_types_sql.sql

Change from quotes to backticks for BQ

---

run_test.sh

Closes #540
This is a:
The integration tests passed in CircleCI even though one of the dbt steps failed. This is because the shell script only returns the final exit code -- intermediate exit codes are ignored by default. 
Several options to solve this issue are discussed [here](https://github.com/dbt-labs/dbt-utils/issues/540#issuecomment-1096720063).
Chosen option: `command || exit 1` because it is minimally invasive, low risk, and preserves our optionality in the future.
- solves the immediate problem
- low risk
- minimally invasive and straight-forward
- only requires adding the ` || exit 1` suffix to 5 lines of code
- preserves our optionality in the future
- completely reversible
- doesn't prevent us from pursuing the other ideas like dbt build, etc as the next logical steps to take …

Fail integration tests appropriately

---

README.md

Closes #544
This is a:
This PR adds documentation about the `listagg` cross-db macro to the README as requested by issue #544

fix / added documentation about listagg macro to readme

---

README.md

This is a:
A couple of links are missing the `-source` suffix.

Fix link to macro section

---

doc/arch/README.md
doc/arch/adr-000-documenting-architecture-decisions.md

This is a:
Quoting [Michael Nygard](https://www.cognitect.com/blog/2011/11/15/documenting-architecture-decisions):
> One of the hardest things to track during the life of a project is the motivation behind certain decisions. A new person coming on to a project may be perplexed, baffled, delighted, or infuriated by some past decision.
Therefore:
> We will keep a collection of records for "architecturally significant" decisions: those that affect the structure, non-functional characteristics, dependencies, interfaces, or construction techniques.
This PR seeds Nygard's original problem/solution [strange loop](https://en.wikipedia.org/wiki/Strange_loop) into our project using the minimal amount of …

Use the ADR (Architectural Design Record) pattern for documenting significant decisions

---

CHANGELOG.md
CONTRIBUTING.md
README.md

This is a:
* Explain in more detail how a contributor can get from A to Z
* Put the instructions in a conventional CONTRIBUTING.md file
* Align with patterns and wording within [dbt-core](https://github.com/dbt-labs/dbt-core/)

Stand-alone guide to contributing

---

README.md

This is a:
There is some unnecessary and non-functional trailing whitespace in the README.
Some contributors have editors set to automatically trim this type of whitespace, and it leads to diffs that are harder to read.
If we just axe the extra whitespace, problem solved 😄

Remove extraneous trailing whitespace

---

integration_tests/models/sql/schema.yml

resolves #579
This is a:
The integration test for the `deduplicate` macro will run now:
```
02:01:33  47 of 88 PASS dbt_utils_equality_test_deduplicate_ref_data_deduplicate_expected_  [PASS in 3.26s]
```

Fix deduplicate test

---

integration_tests/models/generic_tests/schema.yml

resolves #558
This is a:
For our integration tests, we had our seeds under the `models` key in our YAML configuration. dbt will emit a warning for each case. The solution is very simple: just move it under the `seeds` key instead!
Note: this will leave any deprecation warnings in place when running integration tests. Those warning will remain until we fully remove that functionality within a major release that contains breaking changes.

Place the seed node specifications under the seeds key

---

CHANGELOG.md
README.md
integration_tests/data/sql/data_get_column_values_where.csv
integration_tests/data/sql/data_get_column_values_where_expected.csv
integration_tests/models/sql/schema.yml
integration_tests/models/sql/test_get_column_values_where.sql
macros/sql/get_column_values.sql

Closes #511 closes #582
This is a:
Closes #511 & redundant #582. Adds a `where` clause parameter to the `get_column_values` macro to enable filtering the returned columns.

Add optional where clause to get_column_values

---

.circleci/config.yml
CHANGELOG.md

Resolves #584
This is:
Two things:
- upgrade to a next-gen docker convenience image in CircleCI
- change from patch version image to a minor version
The latter is so we will automatically utilize new patch versions of the convenience image as they are rolled out.

Replace legacy CircleCI PostgreSQL convenience image

---

CHANGELOG.md
README.md
integration_tests/models/sql/schema.yml
integration_tests/models/sql/test_union_where.sql
integration_tests/models/sql/test_union_where_base.sql
macros/sql/union.sql

Resolves #464, resolves #382
This is a:
I often want to add basic filters when using `union_relations`, such as excluding obsolete records or low-quality data. Currently, I have to create two models to do so: one to union the data then another to filter it. This PR adds a `where` parameter to `union_relations` so models are filtered _before_ being unioned.
More context & discussion can be found in #464 and #382.

Add `where` parameter to `union_relations`

---

CHANGELOG.md
README.md
integration_tests/models/sql/schema.yml
integration_tests/models/sql/test_deduplicate.sql
integration_tests/models/sql/test_deduplicate_deprecated.sql
macros/sql/deduplicate.sql

This is a:
This Pull Request aims to improve the `deduplicate` macro based on community feedback from its first release. It is stacked on top of #549 and introduces breaking changes.
- #542 discusses argument naming as well as how to improve the documentation.
- #542 also raises the issue that the usage of `relation_alias` to reference CTEs is confusing. This prompted me to investigate whether this is really needed - it was only needed due to the use of `dbt_utils.star` which can be avoided by using a `natural join` which is supported by most SQL syntaxes.

Refactor `deduplicate()` arguments

---

README.md

This is a:
Adds slugify to the list of Jinja Helper macros in the README

Add slugify to list of Jinja Helpers

---

macros/sql/star.sql

Fixes #605
This is a:
I have been using sqlfluff to lint my dbt sql code. Sqlfluff relies on the dbt compiled code to lint. When dbt_util.star is called with a reference that does not yet exist (parsing mode) without running `dbt run` it does not know how to handle `get_filtered_columns_in_relation` being empty. This PR should add the case where if `get_filtered_columns_in_relation` is empty it will replace the entire dbt_utils query with a star. This allows the compiled version to be properly linted without a parsing error. 
Previously:
```SQL
SELECT
FROM "Table.Name"
```
Now:
```SQL
SELECT *
FROM "Table.Name"
```
I'm not sure if the submitted ["fix"](https://github.com/dbt-labs/dbt-utils/pull/532/files) for this in Release 0.8.3 works as intended, but should be reviewed by someone more …

star macro: conditional check to see if cols contains columns, if not replace with *

---

CHANGELOG.md
macros/sql/union.sql

This is a:
Fixes #606
Thanks to @erika-e for reporting the issue with `dbt_utils.union_relations` on dbt Cloud and @jeremyyeo for figuring out what was happening and how to solve it.
Based on the description in #606, I'm guessing [slim CI](https://docs.getdbt.com/docs/dbt-cloud/using-dbt-cloud/cloud-enabling-continuous-integration) or something similar was being used. Regardless, I think we have a fix that will support other use-cases too, like [SQLFluff](https://www.sqlfluff.com/).
I considered several variations for the implementation.
[`flags.WHICH`](https://docs.getdbt.com/reference/dbt-jinja-functions/flags) isn't very well documented, but it identifies the dbt subcommand that is executing. It …

Only raise error within `union_relations` for build/run sub-commands

---

README.md

This is a:
The yml indentation in the README is inconsistent. As someone who is not a yml expert but tries to stay consistent, wants my team to be consistent, and aspires to mostly get my yml indentation right on the first go, it is confusing to see inconsistency in the README.

standardize yml indentation under the 'models:' line on the README

---

doc/arch/README.md
docs/decisions/README.md
docs/decisions/adr-0000-documenting-architecture-decisions.md
docs/decisions/adr-0001-decision-record-format.md

This is a:
See [ADR-0001](https://github.com/dbt-labs/dbt-utils/blob/fd041f70e722a5decc09eae0424df62e5f0d6823/docs/decisions/adr-0001-decision-record-format.md) for details.

Use MADR 3.0.0 for formatting decision records

---

docs/decisions/adr-0002-cross-database-utils.md

This is a:
See [ADR-0002](https://github.com/dbt-labs/dbt-utils/blob/c233d44242984e06eb4541d51bc69e6680af7855/docs/decisions/adr-0002-cross-database-utils.md) for details.

MADR decision record for moving cross-database macros into dbt-core + adapters

---

CHANGELOG.md
README.md
integration_tests/models/sql/schema.yml
integration_tests/models/sql/test_union_no_source_column.sql
integration_tests/tests/generic/expect_table_columns_to_match_set.sql
macros/sql/union.sql

This is a:
This covers issue #331, which allows passing in `none` in order to omit a `source_column_name` column when unioning.

Feature: Add option to remove the source_column_name on the union_relations macro

---

dbt_project.yml
macros/cross_db_utils/any_value.sql
macros/cross_db_utils/bool_or.sql
macros/cross_db_utils/cast_bool_to_text.sql
macros/cross_db_utils/concat.sql
macros/cross_db_utils/datatypes.sql
macros/cross_db_utils/date_trunc.sql
macros/cross_db_utils/dateadd.sql
macros/cross_db_utils/datediff.sql
macros/cross_db_utils/escape_single_quotes.sql
macros/cross_db_utils/except.sql
macros/cross_db_utils/hash.sql
macros/cross_db_utils/intersect.sql
macros/cross_db_utils/last_day.sql
macros/cross_db_utils/length.sql
macros/cross_db_utils/listagg.sql
macros/cross_db_utils/literal.sql
macros/cross_db_utils/position.sql
macros/cross_db_utils/replace.sql
macros/cross_db_utils/right.sql
macros/cross_db_utils/safe_cast.sql
macros/cross_db_utils/split_part.sql
macros/cross_db_utils/xdb_deprecation_warning.sql
macros/materializations/insert_by_period_materialization.sql

This is a:
The cross-db macros have been moved to dbt Core in v1.2. They already were dispatched to the `dbt` project, but now there are also deprecation warnings which will show during compilation. I've also bumped the min dbt version to 1.2-rc1. 
I think that with these changes, we could release utils 0.9.0-rc1 immediately, and release 0.9.0 final when 1.2 final ships.

dbt Core 1.2 and utils 0.9.0 prep

---

macros/sql/get_table_types_sql.sql
macros/sql/get_tables_by_pattern_sql.sql

Resolves https://github.com/dbt-labs/dbt-utils/issues/572

Use adapter.quote() for get_table_types_sql

---

README.md

The not_accepted_values macro was missing from the README table of contents, adding it in.
This is a:

Add not_accepted_values to README ToC

---

README.md
integration_tests/tests/generic/expect_table_columns_to_match_set.sql
macros/cross_db_utils/cast_array_to_string.sql
macros/cross_db_utils/current_timestamp.sql
macros/generic_tests/cardinality_equality.sql
macros/generic_tests/equality.sql
macros/generic_tests/recency.sql
macros/generic_tests/sequential_values.sql
macros/materializations/insert_by_period_materialization.sql
macros/sql/date_spine.sql
macros/sql/surrogate_key.sql
macros/sql/union.sql
macros/sql/unpivot.sql
macros/sql/width_bucket.sql
macros/web/get_url_host.sql
macros/web/get_url_parameter.sql
macros/web/get_url_path.sql

This PR removes internal references to deprecated `dbt_utils` macros in favor of their `dbt-core` counterparts.
Closes #656 
This is a:
Several dbt-utils macros internally reference deprecated macros using the `dbt_utils` namespace. This triggers warnings in downstream models and packages.

Remove cross-db dbt_utils references

---

CHANGELOG.md
macros/sql/star.sql

This is a:
After the release of sqlfluff 1.3.0, we had some errors because the star macro was generating new lines before the macro. This PR fix it.

Remove unnecessary generated new lines in star.sql

---

CHANGELOG.md
macros/sql/union.sql

source_column_name need a [none test](https://stackoverflow.com/questions/19614027/jinja2-template-variable-if-none-object-set-a-default-value) not "!="
resolves #
This is a:
- [* ] bug fix with no breaking changes
Fix source_column_name check in union_relations
- [*] BigQuery
- [*] I have added an entry to CHANGELOG.md

fix: source_column_name none

---

macros/sql/union.sql

resolves #664 
This is a:
This updates the `string_literal` cross db macro in `union_relations` to use the core version rather than the dbt_utils version to avoid deprecation warnings.

update union_relations to use core string literal macro

---

CHANGELOG.md
integration_tests/models/sql/schema.yml
integration_tests/models/sql/test_safe_add.sql
integration_tests/models/sql/test_surrogate_key.sql
macros/sql/safe_add.sql
macros/sql/surrogate_key.sql

Closes #667.
This is a:
Remove the `varargs` usage in `surrogate_key`, which now only takes a single list argument.

Fully remove varargs usage in surrogate_key and safe_add

---

LICENSE

I want to give proper attribution and licensing to code from dbt_utils that I'm using, so made this fix. Hope it's ok.
resolves #
This is a:

Update from template to dbt copyright

---

README.md

resolves #
This is a:
Corrects the link to the contributing guide from the README; I was looking for it for #686 and noticed it ws broken.

Correct link from README to the CONTRIBUTING guide.

---

macros/generic_tests/mutually_exclusive_ranges.sql

resolves N/A
This is a:
Typo fix

Fix typo in comment in `mutually_exclusive_ranges`

---

CHANGELOG.md
macros/sql/pivot.sql

resolves #689
This is a:
In a new version of dbt-core, the `escape_single_quotes` macro is part of core, so it's no longer necessary to reference the version in dbt utils and in fact usage of it is raising a warning that the function will be removed in future versions.

Change `escape_single_quotes` Reference in Pivot Macro

---

integration_tests/data/sql/data_safe_divide_numerator_expressions.csv
integration_tests/models/sql/test_safe_divide.sql

resolves safe_divide integration test errors
This is a:

fix syntax errors 

---

CHANGELOG.md
integration_tests/data/sql/data_safe_divide_numerator_expressions.csv
integration_tests/models/sql/test_safe_divide.sql
macros/generic_tests/cardinality_equality.sql
macros/generic_tests/equality.sql
macros/generic_tests/recency.sql
macros/generic_tests/sequential_values.sql
macros/sql/date_spine.sql
macros/sql/generate_surrogate_key.sql
macros/sql/pivot.sql
macros/sql/union.sql
macros/sql/unpivot.sql
macros/sql/width_bucket.sql
macros/web/get_url_host.sql
macros/web/get_url_parameter.sql
macros/web/get_url_path.sql

resolves #690 
This is a:
Adding dbt. prefix(namespace) to all the migrated cross database macros to solve the bug that caused unexpected behavior when a project already had a macro named the same as one of the migrated cross-db macros.
I did not touch the macro call in the test folders (they still call dbt_utils

Restore dbt. prefix for all migrated cross-db macros

---

CHANGELOG.md
README.md
integration_tests/models/generic_tests/schema.yml
macros/generic_tests/expression_is_true.sql

Closes #695 
This is a:
Remove `condition` argument since it can be replaced by `where`.

Remove obsolete condition argument from expression_is_true

---

CHANGELOG.md
macros/cross_db_utils/deprecated/xdb_deprecation_warning.sql

resolves #722, resolves #720, resolves #712 
This is a:
Fixes the issue where cross-db deprecation warnings are shown during project parsing, which means they come up even in macros which have migrated to the new code

Add if execute checks to xdb deprecation warnings

---

integration_tests/models/sql/schema.yml
integration_tests/models/sql/test_star_no_columns.sql
macros/sql/star.sql

resolves #681 
This is a:
#561 solved a SQLFluff linting error where the `star()` macro returned an empty string if there were no columns found (either because the model doesn't exist or because all columns were excluded). 
The side effect of this is that if someone excludes all columns, they get `'*'` (every column) back instead, which is the exact opposite of what you'd expect. 
This change means that if no columns are found, it returns `'no columns returned from star() macro' as outcome_msg` instead. 
This is still valid SQL, so SQLFluff won't complain about it, but it better represents the outcome that got us here than a `*`.

Output a warning when star finds no columns, not '*'

---

README.md

Suggested by https://github.com/dbt-labs/dbt-utils/issues/736#issuecomment-1345796233
Add link to the where's reference page and update the syntax.
(@s-t-hg cannot create a PR on my account in an organization, so I created a PR on my private account)
This is a:

Update README.md about use `where` with `accepted_range` tests

---

README.md

resolves #759 
This is a:
SQL supports two primary ways to combine query results: `union` (de-duping row-wise) and `union all` (no de-duping). The documentation for the `union_relations()` macro should be clear about which is used here.

doc: clarify that `union_relations()` uses `union all`

---

macros/sql/generate_surrogate_key.sql

resolves #755
This is a:
This pull request solves a problem with empty lines in the `generate_surrogate_key` macro, that causes sqlfluff linting fails for the compiled code.

fix: #755 - add whitespace control to generate_surrogate_key macro

---

README.md
integration_tests/data/sql/data_safe_subtract.csv
integration_tests/models/sql/schema.yml
integration_tests/models/sql/test_safe_subtract.sql
macros/sql/safe_subtract.sql

resolves #745
This is a:
As discussed in #745, this new macro will provide a method for taking the difference across nullable fields similar in functionality to `safe_add()`. Currently it is necessary to multiply fields by -1 with the `safe_add()` macro or use coalesce statements in sql directly to achieve the same result.

Safe subtract

---

CHANGELOG.md
macros/sql/get_table_types_sql.sql

resolves [#768](https://github.com/dbt-labs/dbt-utils/issues/768)
This is a:
`get_relations_by_pattern` throws an error when using the databricks adapter on schemas in a Unity catalog. The error comes from the table having the `table_type` `MANAGED` in the `information_schema.tables` table.
Adding a handler for databricks allows the macro to as expected with data in a Unity catalog.

Add Databricks handler for get_table_types_sql.sql

---

integration_tests/tests/sql/test_get_column_values_use_default.sql

resolves N/A
This is a:
Please reformat the Jinja comment however desired.
Context: merge queue auto-merged prior to [this](https://github.com/dbt-labs/dbt-utils/pull/771/files/51d883ad7dfcb9f1dee2a4fcc43dc41482c8d42d#diff-ff359ddba6bdd617553825ded6e10db24b4305a79f3490ca965b1c43d7d88324) suggestion being committed that adds a link to https://github.com/dbt-labs/dbt-utils/issues/788 as an inline comment.
N/A

Point to the GitHub issue for re-enabling this test

---

CHANGELOG.md
README.md

resolves #790
This is a:
`safe_divide` and `width_bucket ` didn't get their source code URLs updated when they changed source code directories, so clicking on links in the readme gives 404 like this:

Fix legacy links in README

---

.github/workflows/create-table-of-contents.yml

Please merge this update today! [node 12 support dropping tomorrow](https://github.blog/changelog/2023-05-04-github-actions-all-actions-will-run-on-node16-instead-of-node12/) and these version updates to Github Actions get ahead of that. Resolves RELENG-144

update used gh actions ahead of node12 deprecation

---

CHANGELOG.md
integration_tests/models/generic_tests/schema.yml
macros/generic_tests/at_least_one.sql

resolves #775 
[This is a:
](https://github.com/JoshuaHuntley)

Improve the performance of the at_least_one test

---

CHANGELOG.md
macros/sql/deduplicate.sql

resolves https://github.com/dbt-labs/dbt-utils/issues/713
This is a:
In Redshift `deduplicate` macro causes rows with NULL values in any column to be discarded due to specifics of the natural join.
Since Redshift has added support for QUALIFY keyword (https://aws.amazon.com/about-aws/whats-new/2023/07/amazon-redshift-qualify-clause-select-sql-statement/) we can get rid of natural join in the macro and fix the problem in an elegant manner.
Compare inputs and outputs:
```sql
with data as (
select 
'2021-04-03 23:00:26'::timestamp as ts,
1 AS id,
NULL AS null_field
UNION ALL
select 
'2021-04-03 23:00:26'::timestamp as ts,
1 AS id,
NULL AS null_field
),
data_deduped AS (
with row_numbered as (
select …
```

Use QUALIFY clause in `deduplicate` macro for Redshift

---

CHANGELOG.md
macros/sql/get_tables_by_pattern_sql.sql

redshift external tables are not listed in information_schema.tables  but we can extract the same info from svv_external tables and union the results. also quote database name as redshift allows dashes which require quotes
resolves #752 
This is a:
external tables in redshift are not listed in information_schema.tables
they are listed in svv_external_tables
so that this macro works as expected (lists all tables in the specified schema, whether external or not)
there is a new dispatch for redshift__get_tables_by_pattern_sql which calls the default macro
and unions the result with the same information (with the same pattern matching) from svv_external_tables.
redshift also allows dashes in database …

get redshift external tables

---

dev-requirements.txt
integration_tests/package-lock.yml

Our CI is broken because pip syntax has changed for direct git references of packages
This is a:
We want the package to work.

Update dev-requirements for new pip syntax

---

CHANGELOG.md
README.md

Set the correct language identifier in the code block of the document

---

README.md

This is a:
I was looking if `not_null_proportion` supported grouping and noticed this inconsistency in the README which confused me about which was the correct spelling. It is a small change, but hopefully avoids confusion for people looking at it in the future.

Typo of `not_null_proportion` in README.md

---

README.md

FIX: Failing example for dbt_utils.deduplicate() in README.md

---

README.md

resolves #863
This is a:
The current URL is returning 404, so the recommendation is to update it to link to Wikipedia instead.
N/A for documentation updates

Link to Haversine Distance article on Wikipedia

---

README.md
dbt_project.yml
integration_tests/data/schema_tests/schema.yml
integration_tests/models/datetime/schema.yml
integration_tests/models/generic_tests/schema.yml
integration_tests/models/geo/schema.yml
integration_tests/models/sql/schema.yml
integration_tests/models/web/schema.yml

resolves #894
This is a:
With the new dbt-core `v1.8`, the syntax for data tests have updated from `tests:` to `data_tests:`. This PR updates that syntax to get rid of the warning message.

update tests: -> data_tests:

---

.github/pull_request_template.md

resolves #902
This is a:
We have a checklist item reminding contributors to manually update the changelog. But we have been using the "Generate release notes" button in GitHub in place of manual [changelog](https://github.com/dbt-labs/dbt-utils/blob/main/CHANGELOG.md) entries. So any changelog entries that are merged are just overwritten during the release.
Also, we have a long checklist, which lowers its utility.
- Remove "I have added an entry to CHANGELOG.md" from the PR template 
- Checklist is one item shorter

Remove "I have added an entry to CHANGELOG.md" from the PR template

---

.github/pull_request_template.md

resolves #904
This is a:
Our PR template is pretty long, which makes it onerous to use. Many items are already covered in our contribution guidelines in [their own section](https://github.com/dbt-labs/dbt-utils/blob/85ade29c3e69bed3a13812c716c19eea9a0551c4/CONTRIBUTING.md#implementation-guidelines).
Replace (4) checklist items with (1) checklist item that says:
> - [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-utils/blob/main/CONTRIBUTING.md) and understand what's expected of me

Add a PR checklist item for "I have read the contributing guide..." as a catch-all

---

.github/pull_request_template.md

resolves #908
Our PR template is pretty long, which makes it onerous to use. It is also unnecessarily different from the PR templates of dbt-core, dbt-adapters, etc.
We already use GitHub labels like `bug`, `enhancement`, and `documentation` on issues to indicate the type of change. Since we require associated issues for each PR, we can use those labels and remove the related checklist items from the PR template. This will make things quite a bit shorter and easier to read PR descriptions 😎
- [N/A] I have run this code in development and it appears to resolve the stated issue
- [N/A] This PR includes tests, or tests are not required/relevant for this PR
- [N/A] I have updated the README.md (if applicable)

Remove the PR checklist items related to the type of change

---

CONTRIBUTING.md

resolves #914
We use [automatically generated release notes](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes) to generate `CHANGELOG` entries now, so our contributing guide is out-of-date.
Bring the contributing guide up-to-date by updating the language and adding a hyperlink to the "automatically generated release notes" feature in GitHub.
- [N/A] I have run this code in development and it appears to resolve the stated issue
- [N/A] This PR includes tests, or tests are not required/relevant for this PR
- [N/A] I have updated the README.md (if applicable)

Contributors shouldn't edit the `CHANGELOG.md` directly anymore

---

integration_tests/ci/sample.profiles.yml
integration_tests/dbt_project.yml

resolves #925
The [migration guide for v1.8](https://docs.getdbt.com/docs/dbt-versions/core-upgrade/upgrading-to-v1.8#managing-changes-to-legacy-behaviors) includes:
> - Custom defaults of [global config flags](https://docs.getdbt.com/reference/global-configs/about-global-configs) should be set in the flags dictionary in [dbt_project.yml](https://docs.getdbt.com/reference/dbt_project.yml), instead of in [profiles.yml](https://docs.getdbt.com/docs/core/connect-data-platform/profiles.yml). Support for profiles.yml has been deprecated.
Move from `config:` from `profiles.yml` to `flags:` in `dbt_project.yml`.

Move profiles config to project flags

---

README.md

resolves #930
There is a list of macro names without links.
Add links to make them easier to look up.

Link to tests that support `group_by_columns`

---

README.md

resolves #932
The description for the `at_least_one` data test lacks specificity.
Be more explicit by clarifying that it applies to non-`null` values.

Expand description for the `at_least_one` data test

---

integration_tests/data/schema_tests/data_test_at_least_one.csv
integration_tests/models/generic_tests/schema.yml
macros/generic_tests/at_least_one.sql

resolves #838 
The pruning logic introduced in #776 disrupted the grouping behavior in the `at_least_one` test.
Specifically, the initial `pruned_rows` CTE includes a `limit 1` statement, which selects a single record where the target column is not null.
As a result, the test passes inappropriately when the `group_by_columns` parameter is configured, as long as the target column has at least one not-null value.
Essentially, the `group_by_columns` parameter currently has no effect on the test. It evaluates target column values as a single group, regardless of whether or not the parameter is present.
Restore the `at_least_one` test to its prior state.
Since the goal of #776 was to improve the performance of the test, I also considered a set-logic approach to evaluating a column at the group …

Revert pruning in `at_least_one` test

---

.github/workflows/ci.yml

resolves #971
PRs from forks will fail CI because the PR trigger is `pull_request` so they do not have access to teh repo vars that are needed since the workflow runs in the context of the fork.  
Update to trigger off `pull_request_target` and the workflow runs in the context of the base branch (this repo).
Does not require a release since it only affect local CI

Use pull_request_target trigger

---

dev-requirements.txt

resolves #990
> `dbt-postgres` moved to the `dbt-adapters` monorepo. So `dbt_utils` is now pointing to a stale version of `dbt-postgres`
See https://github.com/dbt-labs/dbt-adapters/pull/615 for more detail.
Update the refs so that it points to [`dbt-postgres` subdirectory](https://github.com/dbt-labs/dbt-adapters/tree/main/dbt-postgres) within the `dbt-adapters` monorepo.

Update `dev-requirements.txt` to use the `dbt-adapters` monorepo

---

.github/CODEOWNERS

resolves https://github.com/dbt-labs/dbt-utils/issues/997
The `.github/CODEOWNERS` file is out of date.
Bring it up to date by assigning the appropriate team.

Update `CODEOWNERS` file
